spring:
  application:
    name: sistema-punto-ventas-web
  
  datasource:
    url: jdbc:mysql://localhost:3306/punto_de_ventas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8091
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:miClaveSecretaSuperSeguraParaJWT2024PuntoDeVentas}
  expiration: 86400000 # 24 horas en milisegundos

logging:
  level:
    com.sistema.puntoventas: DEBUG
    org.springframework.security: DEBUG
